INSERT INTO words (english_word, russian_translation)
VALUES ('hello', 'привет'),
       ('world', 'мир'),
       ('apple', 'яблоко'),
       ('book', 'книга'),
       ('computer', 'компьютер'),
       ('keyboard', 'клавиатура'),
       ('mouse', 'мышь'),
       ('monitor', 'монитор'),
       ('phone', 'телефон'),
       ('house', 'дом'),
       ('car', 'машина'),
       ('tree', 'дерево'),
       ('flower', 'цветок'),
       ('sun', 'солнце'),
       ('moon', 'луна'),
       ('star', 'звезда'),
       ('water', 'вода'),
       ('fire', 'огонь'),
       ('wind', 'ветер'),
       ('earth', 'земля');